### ISSUE TITLE
Safe co-iteration along axes

### ISSUE THREAD

**Issue by Tokazama** [SciML/ArrayInterface.jl#62]
This came up with the following comment in from #61 .

> Users will often check for equal sizes in front of a loop, and eachindex will guarantee this as well
> ```julia
> for I in eachindex(A,C) # checks for equivalent size
>    
> end
> ```
> Because eachindex isn't always appropriate (e.g., when you don't have exact correspondence between axes of the arrays), I think it'd be a good to have something like an eachindexalongaxis:
> 
> ```julia
> function mymatmulkernel!(C, A, B)
>     @avx for m in eachindexalongaxis((C,A),(1,1)), n in eachindexalongaxis((C,B),(2,2)), k in eachindexalongaxis((A,B),(2,1))
>         C[m,n] += A[m,k] * B[k,n]
>     end
> end
> ```
> where it checks sizes. eachindexalongaxis or each_index_along_axis doesn't really roll off > the tongue, and I don't know where such a function should live.
> I'd also have to think a little more about how to use it and actually pass the information of > dimension equality (to be combined with density guarantees) to deduce stride-equality. The hacky way would be to just pattern match eachindex and eachindexalongindex in the macro, handling dimension equality through the expression, while handling density info based on types.

I'd like to propose the use of `indices` for specifically retrieving the iterator that corresponds to each axis of an array. It would function like `axes` but if there's any sort of other data associated with an axis it throws it away so there's a clear relationship between memory layout and and each dimension.

In practice it would look like this:
```julia
julia> indices(ones(2,3))
(Base.OneTo(2), Base.OneTo(3))

julia> indices(ones(2,3), 1)
Base.OneTo(2)

julia> indices(ones(2,3), 2)
Base.OneTo(3)

julia> indices(ones(2,3), ones(2,3), 2)
Base.OneTo(3)

julia> indices(ones(2,3), ones(2,2), 2)
ERROR: DimensionMismatch("all inputs to indices must have the same indices, got Base.OneTo(3) and Base.OneTo(2)")
```

In this case the first several examples are the same as if using `axes`, but it helps for cases like those in AxisIndices.jl where each axis can have additional information (e.g., keys) associated with the indices. The last two examples would ensure that the iterator for each collection is the same along the second dimension.

**Comment by chriselrod** [comment]
In my example I used a tuple of indices, so that we could
```julia
julia> indices(ones(2,3), ones(2,2), (1,1))
Base.OneTo(2)

julia> indices(ones(2,3), ones(2,2), (1,2))
Base.OneTo(2)

julia> indices(ones(2,3), ones(2,2), (2,1))
ERROR: DimensionMismatch("all inputs to indices must have the same indices, got Base.OneTo(3) and Base.OneTo(2)")

julia> indices(ones(2,3), ones(2,2), (2,2))
ERROR: DimensionMismatch("all inputs to indices must have the same indices, got Base.OneTo(3) and Base.OneTo(2)")
```
As we may wish to iterate across different axes for the different arrays. My example also used two tuples, as it's easier to define a function in this way:
```julia
indices(A::AbstractArray, i::Integer) = axes(A, i)
@inline index_tuple(i::Integer, n) = i # either index into `i`, or return it, depending on whether it's a tuple or scalar
@inline index_tuple(i::Tuple{Vararg{<:Integer}}, n) = i[n]
function indices(A::Tuple{Vararg{<:AbstractArray,N}}, i) where {N}
    inds = ntuple(n -> axes(A[n], index_tuple(i, n)), Val(N))
    ind = first(inds)
    @assert all(isequal(ind), Base.tail(inds)) "Not all specified axes are equal: $inds"
    ind
end
```
This should have more or less the desired behavior.

**Comment by Tokazama** [comment]
> As we may wish to iterate across different axes for the different arrays.

That's a really good point.

I've actually really wanted this feature, so if people like this I can make a PR.

**Comment by chriselrod** [comment]
Sounds good.
As an obvious improvement to my definition, it should try to return the most specific axis information available, e.g. favoring `Base.OneTo` over `UnitRange`, rather than just returning the first axis.
