### ISSUE TITLE
contiguous_axis_indicator for arrays with unknown contiguity

### ISSUE THREAD

**Issue by jipolanco** [SciML/ArrayInterface.jl#84]
Currently, `contiguous_axis` returns `nothing` for an array type with unknown contiguity properties. However, for the same array type, `contiguous_axis_indicator` is undefined, as there is no defined `contiguous_axis_indicator(::Nothing, ::Val)` method.

Is this intentional? If not, would it make sense here to return `nothing`, just like for `contiguous_axis`?

Minimal example:

```julia
import ArrayInterface: contiguous_axis, contiguous_axis_indicator

# Define dummy array type with unknown contiguity properties
struct DummyArray{T,N} <: AbstractArray{T,N}
    dims :: Dims{N}
    DummyArray{T}(::UndefInitializer, dims...) where {T} = new{T,length(dims)}(dims)
end
Base.size(x::DummyArray) = x.dims
Base.getindex(::DummyArray{T}, inds...) where {T} = zero(T)

A = DummyArray{Float64}(undef, 3, 5)
contiguous_axis(A)            # returns nothing
contiguous_axis_indicator(A)  # MethodError: no method matching contiguous_axis_indicator(::Nothing, ::Val{2})
```

**Comment by chriselrod** [comment]
Yes, it should return `nothing` as well.

The idea is that these would be used for optimizations. If the information isn't available, you'd want to run a fallback.

**Comment by jipolanco** [comment]
Got it, thanks! I'll submit a PR.
