### ISSUE TITLE
WARNING: Wrapping Vararg directly in UnionAll is deprecated (wrap the tuple instead)

### ISSUE THREAD

**Issue by DilumAluthge** [SciML/ArrayInterface.jl#99]
See also: https://github.com/chriselrod/LoopVectorization.jl/issues/175

cc: @chriselrod

**Comment by DilumAluthge** [comment]
@chriselrod I'm closing this as fixed by https://github.com/SciML/ArrayInterface.jl/commit/57b03b300433c2bce2ffdc8ade97682b096bef89, correct?

**Comment by chriselrod** [comment]
Should be fixed, yes.
